import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Navbar from "@/components/Navbar/navbar";
import Footer from "@/components/Footer/footer";


export const metadata: Metadata = {
  title: "Saheda Consulting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-slate-400">
        <Navbar />
        <ToastContainer />
        <div className=" min-h-screen text-black dark:text-white bg-gradient-to-b from-gray-200 to-white dark:from-black dark:to-black ">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
